[package]
name = "yah-plugin-wasm"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "Provisional WIT contract and Wasmtime component driver for YAH"

[dependencies]
wasmtime.workspace = true
yah-plugin-host = { path = "../yah-plugin-host" }

[dev-dependencies]
libc.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
wit-bindgen.workspace = true
yah-compose = { path = "../yah-compose" }
wit-parser.workspace = true
