export type WireCodecErrorCode =
  | "FRAME_EMPTY"
  | "FRAME_TOO_LARGE"
  | "INVALID_UTF8"
  | "INVALID_JSON"
  | "DUPLICATE_MEMBER"
  | "UNSAFE_INTEGER"
  | "NON_FINITE_NUMBER"
  | "INVALID_UNICODE"
  | "INVALID_HOST_MESSAGE"
  | "INVALID_WORKER_MESSAGE"
  | "CONTROL_FRAME_TOO_LARGE"
  | "INVALID_OUTBOUND_VALUE"
  | "CYCLIC_OUTBOUND_VALUE";

const messages: Readonly<Record<WireCodecErrorCode, string>> = Object.freeze({
  FRAME_EMPTY: "frame declaration is zero",
  FRAME_TOO_LARGE: "frame exceeds the generated byte bound",
  INVALID_UTF8: "frame payload is not valid UTF-8",
  INVALID_JSON: "frame payload is not one complete JSON value",
  DUPLICATE_MEMBER: "JSON object contains a duplicate member name",
  UNSAFE_INTEGER: "JSON integer is outside the I-JSON safe range",
  NON_FINITE_NUMBER: "JSON float is not finite",
  INVALID_UNICODE: "JSON string contains an unpaired surrogate",
  INVALID_HOST_MESSAGE: "JSON value is not a host message",
  INVALID_WORKER_MESSAGE: "value is not a worker message",
  CONTROL_FRAME_TOO_LARGE: "control frame exceeds the generated byte bound",
  INVALID_OUTBOUND_VALUE: "worker message contains a value JSON cannot represent unchanged",
  CYCLIC_OUTBOUND_VALUE: "worker message contains a cycle",
});

/** A bounded diagnostic from the byte, JSON, schema, or outbound-value gate. */
export class WireCodecError extends Error {
  readonly code: WireCodecErrorCode;

  constructor(code: WireCodecErrorCode) {
    super(messages[code]);
    this.name = "WireCodecError";
    this.code = code;
  }
}

export function codecError(code: WireCodecErrorCode): WireCodecError {
  return new WireCodecError(code);
}
